<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Starting Appium]]>
    </line>
    <line>
      <![CDATA[Logout dropdown]]>
    </line>
    <line>
      <![CDATA[Inside After class]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="260" started-at="2020-03-16T10:30:19Z" finished-at="2020-03-16T10:30:19Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="260" started-at="2020-03-16T10:30:19Z" finished-at="2020-03-16T10:30:19Z">
      <class name="Test.Logout">
        <test-method status="PASS" signature="Windowcaps()[pri:0, instance:Test.Logout@13c78c0b]" name="Windowcaps" is-config="true" duration-ms="11167" started-at="2020-03-16T16:00:08Z" finished-at="2020-03-16T16:00:19Z">
          <reporter-output>
            <line>
              <![CDATA[Starting Appium]]>
            </line>
          </reporter-output>
        </test-method> <!-- Windowcaps -->
        <test-method status="PASS" signature="BeforeMethod(java.lang.reflect.Method, [Ljava.lang.Object;, org.testng.ITestContext)[pri:0, instance:Test.Logout@13c78c0b]" name="BeforeMethod" is-config="true" duration-ms="21" started-at="2020-03-16T16:00:19Z" finished-at="2020-03-16T16:00:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void Test.Logout.logout() throws java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[Ljava.lang.Object;@2b72cb8a]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[org.testng.TestRunner@7a3793c7]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="FAIL" signature="logout()[pri:0, instance:Test.Logout@13c78c0b]" name="logout" duration-ms="180" started-at="2020-03-16T16:00:19Z" finished-at="2020-03-16T16:00:19Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at Utilities.Reporting.logsGeneration(Reporting.java:216)
	at Pages.LogoutPage.logoutDropdown(LogoutPage.java:29)
	at Test.Logout.logout(Logout.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[Logout dropdown]]>
            </line>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:Test.Logout@13c78c0b]" name="afterMethod" is-config="true" duration-ms="51" started-at="2020-03-16T16:00:19Z" finished-at="2020-03-16T16:00:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="End()[pri:0, instance:Test.Logout@13c78c0b]" name="End" is-config="true" duration-ms="0" started-at="2020-03-16T16:00:19Z" finished-at="2020-03-16T16:00:19Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at Utilities.Reporting.logsGeneration(Reporting.java:216)
	at Utilities.WindowsCapabilitie.End(WindowsCapabilitie.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:336)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[Inside After class]]>
            </line>
          </reporter-output>
        </test-method> <!-- End -->
      </class> <!-- Test.Logout -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
